[project]
name = "multi-mcp-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-genai>=1.19.0",
    "mcp[cli]>=1.9.3",
]

[dependency-groups]
dev = [
    "ruff>=0.11.12",
]
